### Hello world
# @name HelloWorld
GET http://localhost:8080/api

### Get all users
# @name GetAllUsers
GET http://localhost:8080/api/user

### Get user by id
# @name GetUserById
GET http://localhost:8080/api/user/1

### Update user by id
# @name UpdateUser
PUT http://localhost:8080/api/user/1
Content-Type: application/json

{
  "email": "cesar.melendezp96.dev@gmail.com",
  "username": "Mlndz19",
  "password": "MyPwd1996",
  "active": true
}

### Delete user by id
# @name DeleteUser
DELETE http://localhost:8080/api/user/1

### Login
# @name Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "cesar.melendezp96.dev@gmail.com",
  "password": "ElChechal123"
}

### Create new user
# @name RegisterUser
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "cesar.melendezp96.dev@gmail.com",
  "username": "Mlndz19",
  "password": "ElChechal123"
}

### Get All banks
# @name GetAllBanks
GET http://localhost:8080/api/bank

### Get bank by Id
# @name GetBankById
GET http://localhost:8080/api/bank/1

### Create Bank
# @name CreateBank
POST http://localhost:8080/api/bank
Content-Type: application/json

{
  "name": "Santander"
}